services:
  app:
    build: .
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    env_file:
      - .env  # Load environment variables from the .env file
    restart: no  # Automatically restart the container if it crashes
